### ISSUE TITLE
ERROR:root:update_rss -> error: UNIQUE constraint failed: feedentry.id

### ISSUE THREAD

**Issue by drJeckyll** [aigoncharov/telegram-to-rss#1]
Using docker container `aigoncharov/telegram-to-rss:latest` couple of days running OK and then failed after reconnect with:

```
telegram-to-rss  | INFO:telethon.client.telegrambaseclient:Disconnecting borrowed sender for DC 5
telegram-to-rss  | INFO:telethon.network.mtprotosender:Disconnecting from 91.108.56.186:443/TcpFull...
telegram-to-rss  | INFO:telethon.network.mtprotosender:Disconnection from 91.108.56.186:443/TcpFull complete!
telegram-to-rss  | INFO:root:update_rss -> scheduling a new run
telegram-to-rss  | INFO:root:update_rss -> db
telegram-to-rss  | ERROR:root:update_rss -> error: UNIQUE constraint failed: feedentry.id
telegram-to-rss  | ERROR:asyncio:Task exception was never retrieved
telegram-to-rss  | future: <Task finished name='Task-22170' coro=<start_rss_generation.<locals>.update_rss() done, defined at /usr/src/app/telegram_to_rss/server.py:43> exception=IntegrityError(IntegrityError('UNIQUE constraint failed: feedentry.id'))>
telegram-to-rss  | Traceback (most recent call last):
telegram-to-rss  |   File "/usr/local/lib/python3.12/site-packages/tortoise/backends/sqlite/client.py", line 34, in translate_exceptions_
telegram-to-rss  |     return await func(self, query, *args)
telegram-to-rss  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
telegram-to-rss  |   File "/usr/local/lib/python3.12/site-packages/tortoise/backends/sqlite/client.py", line 177, in execute_many
telegram-to-rss  |     await connection.executemany(query, values)
telegram-to-rss  |   File "/usr/local/lib/python3.12/site-packages/aiosqlite/core.py", line 210, in executemany
telegram-to-rss  |     cursor = await self._execute(self._conn.executemany, sql, parameters)
telegram-to-rss  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
telegram-to-rss  |   File "/usr/local/lib/python3.12/site-packages/aiosqlite/core.py", line 129, in _execute
telegram-to-rss  |     return await future
telegram-to-rss  |            ^^^^^^^^^^^^
telegram-to-rss  |   File "/usr/local/lib/python3.12/site-packages/aiosqlite/core.py", line 102, in run
telegram-to-rss  |     result = function()
telegram-to-rss  |              ^^^^^^^^^^
telegram-to-rss  | sqlite3.IntegrityError: UNIQUE constraint failed: feedentry.id
telegram-to-rss  | 
telegram-to-rss  | 
telegram-to-rss  | During handling of the above exception, another exception occurred:
telegram-to-rss  | 
telegram-to-rss  | 
telegram-to-rss  | Traceback (most recent call last):
telegram-to-rss  |   File "/usr/src/app/telegram_to_rss/server.py", line 62, in update_rss
telegram-to-rss  |     raise e
telegram-to-rss  |   File "/usr/src/app/telegram_to_rss/server.py", line 48, in update_rss
telegram-to-rss  |     await update_feeds_in_db(telegram_poller=telegram_poller)
telegram-to-rss  |   File "/usr/src/app/telegram_to_rss/poll_telegram.py", line 216, in update_feeds_in_db
telegram-to-rss  |     await telegram_poller.update_feed(feed_to_update)
telegram-to-rss  |   File "/usr/local/lib/python3.12/site-packages/tortoise/transactions.py", line 57, in wrapped
telegram-to-rss  |     return await func(*args, **kwargs)
telegram-to-rss  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
telegram-to-rss  |   File "/usr/src/app/telegram_to_rss/poll_telegram.py", line 90, in update_feed
telegram-to-rss  |     await FeedEntry.bulk_create(feed_entries)
telegram-to-rss  |   File "/usr/local/lib/python3.12/site-packages/tortoise/queryset.py", line 1936, in _execute
telegram-to-rss  |     await self._db.execute_many(str(self.insert_query), values_lists)
telegram-to-rss  |   File "/usr/local/lib/python3.12/site-packages/tortoise/backends/sqlite/client.py", line 38, in translate_exceptions_
telegram-to-rss  |     raise IntegrityError(exc)
telegram-to-rss  | tortoise.exceptions.IntegrityError: UNIQUE constraint failed: feedentry.id
```

**Comment by fxlrnrpt** [comment]
Could you set "LOGLEVEL" env variable to "DEBUG" and restart the service? It should get us more logs. At first glance, it seems that that message id is duplicated which is kinda... next to impossible.

Alternatively, you could just stop the docker compose stack, run `docker volume rm telegram-to-rss_data` in your terminal and start it again. It is going to nuke everything and fetch the data from scratch. However, it is not an issue since all the data is available on Telegram.

**Comment by drJeckyll** [comment]
First time I deleted db and have to link account again. Now I just setup cronjob to nuke feedentry table ` sqlite3 feeds.db "delete from feedentry;"` on daily basis. 
In any case I set LOGLEVEL to DEBUG, but since I nuke table every 24h it may never happen again.

**Comment by fxlrnrpt** [comment]
Hahaha, good old "just restart it, duh"
Wondering what kind of duplicate ID it could possibly be. My bet that it is some sneaky NULL somewhere that gets serialized somewhere along the way. I'll try to add some extra handlers for that.

**Comment by drJeckyll** [comment]
Not sure if it is the same issue, or it is something different:
```
telegram-to-rss  | ERROR:root:update_rss -> error: Request was unsuccessful 6 time(s)
telegram-to-rss  | ERROR:asyncio:Task exception was never retrieved
telegram-to-rss  | future: <Task finished name='Task-17816' coro=<start_rss_generation.<locals>.update_rss() done, defined at /usr/src/app/telegram_to_rss/server.py:43> exception=ValueError('Request was unsuccessful 6 time(s)')>
telegram-to-rss  | Traceback (most recent call last):
telegram-to-rss  |   File "/usr/local/lib/python3.12/site-packages/telethon/client/downloads.py", line 76, in _request
telegram-to-rss  |     result = await self.client._call(self._sender, self.request)
telegram-to-rss  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
telegram-to-rss  |   File "/usr/local/lib/python3.12/site-packages/telethon/client/users.py", line 87, in _call
telegram-to-rss  |     result = await future
telegram-to-rss  |              ^^^^^^^^^^^^
telegram-to-rss  | telethon.errors.rpcerrorlist.FileMigrateError: The file to be accessed is currently stored in DC 2 (caused by GetFileRequest)
telegram-to-rss  | 
telegram-to-rss  | 
telegram-to-rss  | During handling of the above exception, another exception occurred:
telegram-to-rss  | 
telegram-to-rss  | 
telegram-to-rss  | Traceback (most recent call last):
telegram-to-rss  |   File "/usr/src/app/telegram_to_rss/server.py", line 62, in update_rss
telegram-to-rss  |     raise e
telegram-to-rss  |   File "/usr/src/app/telegram_to_rss/server.py", line 48, in update_rss
telegram-to-rss  |     await update_feeds_in_db(telegram_poller=telegram_poller)
telegram-to-rss  |   File "/usr/src/app/telegram_to_rss/poll_telegram.py", line 216, in update_feeds_in_db
telegram-to-rss  |     await telegram_poller.update_feed(feed_to_update)
telegram-to-rss  |   File "/usr/local/lib/python3.12/site-packages/tortoise/transactions.py", line 57, in wrapped
telegram-to-rss  |     return await func(*args, **kwargs)
telegram-to-rss  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
telegram-to-rss  |   File "/usr/src/app/telegram_to_rss/poll_telegram.py", line 86, in update_feed
telegram-to-rss  |     feed_entries = await self._process_new_dialog_messages(
telegram-to-rss  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
telegram-to-rss  |   File "/usr/src/app/telegram_to_rss/poll_telegram.py", line 153, in _process_new_dialog_messages
telegram-to-rss  |     res_path = await dialog_message.download_media(
telegram-to-rss  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
telegram-to-rss  |   File "/usr/local/lib/python3.12/site-packages/telethon/tl/custom/message.py", line 866, in download_media
telegram-to-rss  |     return await self._client.download_media(self, *args, **kwargs)
telegram-to-rss  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
telegram-to-rss  |   File "/usr/local/lib/python3.12/site-packages/telethon/client/downloads.py", line 418, in download_media
telegram-to-rss  |     return await self._download_photo(
telegram-to-rss  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
telegram-to-rss  |   File "/usr/local/lib/python3.12/site-packages/telethon/client/downloads.py", line 834, in _download_photo
telegram-to-rss  |     result = await self.download_file(
telegram-to-rss  |              ^^^^^^^^^^^^^^^^^^^^^^^^^
telegram-to-rss  |   File "/usr/local/lib/python3.12/site-packages/telethon/client/downloads.py", line 497, in download_file
telegram-to-rss  |     return await self._download_file(
telegram-to-rss  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
telegram-to-rss  |   File "/usr/local/lib/python3.12/site-packages/telethon/client/downloads.py", line 545, in _download_file
telegram-to-rss  |     async for chunk in self._iter_download(
telegram-to-rss  |   File "/usr/local/lib/python3.12/site-packages/telethon/requestiter.py", line 74, in __anext__
telegram-to-rss  |     if await self._load_next_chunk():
telegram-to-rss  |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
telegram-to-rss  |   File "/usr/local/lib/python3.12/site-packages/telethon/client/downloads.py", line 66, in _load_next_chunk
telegram-to-rss  |     cur = await self._request()
telegram-to-rss  |           ^^^^^^^^^^^^^^^^^^^^^
telegram-to-rss  |   File "/usr/local/lib/python3.12/site-packages/telethon/client/downloads.py", line 97, in _request
telegram-to-rss  |     return await self._request()
telegram-to-rss  |            ^^^^^^^^^^^^^^^^^^^^^
telegram-to-rss  |   File "/usr/local/lib/python3.12/site-packages/telethon/client/downloads.py", line 76, in _request
telegram-to-rss  |     result = await self.client._call(self._sender, self.request)
telegram-to-rss  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
telegram-to-rss  |   File "/usr/local/lib/python3.12/site-packages/telethon/client/users.py", line 133, in _call
telegram-to-rss  |     raise ValueError('Request was unsuccessful {} time(s)'
telegram-to-rss  | ValueError: Request was unsuccessful 6 time(s)
```

**Comment by fxlrnrpt** [comment]
@drJeckyll released [0.3.0](https://github.com/aigoncharov/telegram-to-rss/releases/tag/v0.3.0). 

Changelog:
- Reset DB and fetch everything from Telegram from scratch if unrecoverable error is found during an update.
- Gracefully handle media downloading errors.

While it should help you, in fact it is only going to hide the issues with the underlying reason still being there unsolved.
I am keen to figure out what it is going on, so feel free to provide new debug logs if you ever face `UNIQUE constraint failed: feedentry.id`.

In the meantime, closing the issue until new input is provided for further investigation.

**Comment by fxlrnrpt** [comment]
@drJeckyll how is the new release working so far?

**Comment by drJeckyll** [comment]
After update I stopped my fix and so far it's working OK. No issues.

**Comment by stickman33** [comment]
@aigoncharov Its the great instrument because of private chans support! Is there in plans to add video attachment support? Or Im doing smth wrong? Getting "This message has unsupported attachment. Open Telegram to view it." instead of attachment.
